---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seal-secret
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://dmitry-kitsune.github.io/sealed-secret-bitnami/
    targetRevision: 2.4.8
  syncPolicy:
    automated:
      prune: true
