name: kubeconform

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      manifest_file:
        description: 'Path to specific manifest file for validation'
        required: false

permissions:
  contents: read

jobs:
  kubeconform:
    name: Test using kubeconform
    runs-on: ubuntu-latest
    outputs:
      CHECK_OUTPUT: ${{ steps.validate.outputs.CHECK_OUTPUT }}
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
              changed=$(git diff --name-only -r HEAD^1 HEAD | grep -E '\.ya?ml$' || echo "")
              echo "changed_files=$changed" >> $GITHUB_OUTPUT
          else
              changed=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E '\.ya?ml$' || echo "")
              echo "changed_files=$changed" >> $GITHUB_OUTPUT
          fi

      - name: List changed files
        run: |
          if [ -z "${{ steps.changed-files.outputs.changed_files }}" ]; then
            echo "No YAML files were changed. Exiting..."
            exit 0
          fi
          echo "Changed files:"
          echo ${{ steps.changed-files.outputs.changed_files }}

      - name: Set up Kubeconform
        uses: bmuschko/setup-kubeconform@v1

      - name: Validate manifests
        id: validate
        run: |
          CHECK_OUTPUT=""
          for line in $(kubeconform -schema-location default --summary -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' ${{ steps.changed-files.outputs.changed_files }}); do
            CHECK_OUTPUT="${CHECK_OUTPUT} $line"
          done
          echo "CHECK_OUTPUT=$CHECK_OUTPUT" >> $GITHUB_ENV
          echo "::set-output name=CHECK_OUTPUT::$CHECK_OUTPUT"
          echo $CHECK_OUTPUT

      - name: Cache kubeconform schemas
        uses: actions/cache@v3
        with:
          path: ~/.kubeconform
          key: kubeconform-schemas-${{ runner.os }}-${{ github.ref }}

  notification:
    needs: kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: slack-notifi-train
          SLACK_COLOR: ${{ job.status == 'success' && '#36a64f' || '#FF0000' }}
          SLACK_MESSAGE: ${{ needs.kubeconform.outputs.CHECK_OUTPUT }}
          SLACK_TITLE: Kubeconform Validation Results
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

